import PocketBase from 'pocketbase';
import archiver from 'archiver';
import { Readable } from 'stream';

const POCKETBASE_URL = process.env.POCKETBASE_URL;
const POCKETBASE_ADMIN_EMAIL = process.env.POCKETBASE_ADMIN_EMAIL;
const POCKETBASE_ADMIN_PASSWORD = process.env.POCKETBASE_ADMIN_PASSWORD;

function log(level, message, data) {
  const entry = { level, message, timestamp: new Date().toISOString() };
  if (data) entry.data = data;
  console[level](JSON.stringify(entry));
}

async function authenticateUser(pb, authHeader) {
  if (!authHeader || !authHeader.startsWith('Bearer ')) {
    return null;
  }
  const token = authHeader.replace('Bearer ', '');
  try {
    pb.authStore.save(token, null);
    const user = await pb.collection('users').authRefresh();
    return user.record;
  } catch (err) {
    log('warn', 'User auth failed', { error: err.message });
    return null;
  }
}

async function adminAuth(pb) {
  try {
    await pb.admins.authWithPassword(POCKETBASE_ADMIN_EMAIL, POCKETBASE_ADMIN_PASSWORD);
    return true;
  } catch (err) {
    log('error', 'PocketBase admin auth failed', { error: err.message });
    return false;
  }
}

function slugify(text) {
  return (text || 'app')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .substring(0, 50);
}

function generateManifest(appName) {
  const shortName = appName.substring(0, 12);
  return {
    name: appName || 'Generated App',
    short_name: shortName || 'App',
    start_url: './index.html',
    display: 'standalone',
    background_color: '#ffffff',
    theme_color: '#3b82f6',
    icons: [
      { src: './icons/icon-192.png', sizes: '192x192', type: 'image/png' },
      { src: './icons/icon-512.png', sizes: '512x512', type: 'image/png' },
    ],
  };
}

function generateServiceWorker(appName) {
  const cacheName = slugify(appName) + '-v1';
  return `const CACHE_NAME = '${cacheName}';
const ASSETS = ['./', './index.html', './manifest.json'];

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE_NAME).then(c => c.addAll(ASSETS)));
});

self.addEventListener('fetch', (e) => {
  e.respondWith(
    caches.match(e.request).then(r => r || fetch(e.request))
  );
});
`;
}

function generateReadme(appName) {
  return `# ${appName || 'Generated App'}

This app was generated by Prompt-to-PWA.

## Deployment

1. Upload all files to your web server
2. Ensure index.html is served as the default document
3. For HTTPS (required for PWA features), use a service like Netlify, Vercel, or GitHub Pages

## Files

- **index.html** - The complete application (HTML + CSS + JavaScript)
- **manifest.json** - PWA manifest for installable web app
- **sw.js** - Service worker for offline support
- **icons/** - App icons

## Customization

Edit index.html directly to modify the app. All code is in a single file with:
- Tailwind CSS for styling
- Vanilla JavaScript for logic
- localStorage for data persistence
`;
}

function createPlaceholderSvg(size) {
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 ${size} ${size}">
  <rect width="${size}" height="${size}" fill="#3b82f6" rx="${size / 8}"/>
  <text x="${size / 2}" y="${size / 2}" font-family="Arial" font-size="${size / 8}" fill="white" text-anchor="middle" dominant-baseline="central">PWA</text>
</svg>`;
}

function streamToBuffer(stream) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    stream.on('data', (chunk) => chunks.push(chunk));
    stream.on('end', () => resolve(Buffer.concat(chunks)));
    stream.on('error', reject);
  });
}

export default async function handler(event) {
  const corsHeaders = {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Headers': 'Content-Type, Authorization',
    'Access-Control-Allow-Methods': 'GET, OPTIONS',
  };

  if (event.httpMethod === 'OPTIONS') {
    return { statusCode: 204, headers: corsHeaders, body: '' };
  }

  if (event.httpMethod !== 'GET') {
    return {
      statusCode: 405,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      body: JSON.stringify({ error: 'method_not_allowed', message: 'Only GET is allowed' }),
    };
  }

  const jobId = event.queryStringParameters?.jobId;

  if (!jobId) {
    return {
      statusCode: 422,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      body: JSON.stringify({ error: 'invalid_input', message: 'jobId query parameter is required', field: 'jobId' }),
    };
  }

  if (!POCKETBASE_URL) {
    log('error', 'Missing required environment variables');
    return {
      statusCode: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      body: JSON.stringify({ error: 'server_configuration_error', message: 'Server is not configured properly' }),
    };
  }

  const pb = new PocketBase(POCKETBASE_URL);

  // Authenticate user via token
  const user = await authenticateUser(pb, event.headers.authorization);
  if (!user) {
    return {
      statusCode: 401,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      body: JSON.stringify({ error: 'unauthorized', message: 'Invalid or expired session' }),
    };
  }

  // Check if user is Pro
  const fullUser = await pb.collection('users').getOne(user.id);
  if (fullUser.plan_tier !== 'pro') {
    return {
      statusCode: 402,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      body: JSON.stringify({
        error: 'pro_required',
        message: 'Download requires a Pro subscription',
        upgradeUrl: '/settings',
      }),
    };
  }

  // Load the generated_apps record
  let appRecord;
  try {
    appRecord = await pb.collection('generated_apps').getOne(jobId);
  } catch (err) {
    log('error', 'Failed to load app record', { error: err.message, jobId });
    return {
      statusCode: 404,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      body: JSON.stringify({ error: 'not_found', message: 'App record not found' }),
    };
  }

  // Verify ownership
  if (appRecord.user !== user.id) {
    return {
      statusCode: 403,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      body: JSON.stringify({ error: 'forbidden', message: 'You do not own this app' }),
    };
  }

  // Verify app has HTML content
  if (!appRecord.preview_html) {
    return {
      statusCode: 400,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      body: JSON.stringify({ error: 'not_ready', message: 'App has not been compiled yet' }),
    };
  }

  const appName = appRecord.app_name || 'generated-app';
  const appSlug = slugify(appName);

  // Build ZIP archive
  const archive = archiver('zip', { zlib: { level: 9 } });

  // Catch archive errors
  archive.on('error', (err) => {
    log('error', 'Archive error', { error: err.message });
  });

  // Add files to the archive
  archive.append(appRecord.preview_html, { name: 'index.html' });
  archive.append(JSON.stringify(generateManifest(appName), null, 2), { name: 'manifest.json' });
  archive.append(generateServiceWorker(appName), { name: 'sw.js' });
  archive.append(generateReadme(appName), { name: 'README.md' });
  archive.append(createPlaceholderSvg(192), { name: 'icons/icon-192.png' });
  archive.append(createPlaceholderSvg(512), { name: 'icons/icon-512.png' });

  // Finalize the archive
  archive.finalize();

  // Stream to buffer
  let zipBuffer;
  try {
    zipBuffer = await streamToBuffer(archive);
  } catch (err) {
    log('error', 'Failed to build ZIP', { error: err.message });
    return {
      statusCode: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      body: JSON.stringify({ error: 'zip_failed', message: 'Failed to create ZIP archive' }),
    };
  }

  // Update status to downloaded (via admin auth)
  const adminOk = await adminAuth(pb);
  if (adminOk) {
    try {
      await pb.collection('generated_apps').update(jobId, { status: 'downloaded' });
      log('info', 'App downloaded', { jobId, userId: user.id });
    } catch (err) {
      log('warn', 'Failed to update download status', { error: err.message });
    }
  }

  return {
    statusCode: 200,
    headers: {
      ...corsHeaders,
      'Content-Type': 'application/zip',
      'Content-Disposition': `attachment; filename="${appSlug}.zip"`,
    },
    body: zipBuffer.toString('base64'),
    isBase64Encoded: true,
  };
}
